ALTER TABLE books ADD COLUMN IF NOT EXISTS last_cover_update TIMESTAMP DEFAULT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS large_cover_key TEXT DEFAULT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS medium_cover_key TEXT DEFAULT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS small_cover_key TEXT DEFAULT NULL;
